module.exports = {
	rules: {
		indentation: ['tab', {
			ignore: 'value',
		}],
		'color-hex-case': 'lower',
		'color-hex-length': 'short',
		'at-rule-empty-line-before': ['always', {
			except: ['first-nested', 'blockless-after-same-name-blockless'],
		}],
		'at-rule-semicolon-newline-after': 'always',
		'block-closing-brace-newline-before': 'always',
		'block-closing-brace-newline-after': 'always',
		'block-opening-brace-newline-before': 'always',
		'block-opening-brace-newline-after': 'always',
		'declaration-colon-space-before': 'never',
		'declaration-colon-space-after': 'always',
		'length-zero-no-unit': true,
		'number-leading-zero': 'never',
		'number-no-trailing-zeros': true,
		'selector-combinator-space-before': 'always',
		'selector-combinator-space-after': 'always',
		'selector-list-comma-space-before': 'never-single-line',
		'selector-list-comma-space-after': 'never-single-line',
		'selector-list-comma-newline-before': 'never-multi-line',
		'selector-list-comma-newline-after': 'always',
		'shorthand-property-no-redundant-values': true,
		'string-quotes': 'single',
		'declaration-block-properties-order': [
			'content',
			'position',
			'z-index',
			'top',
			'right',
			'bottom',
			'left',
			'flex',
			'flex-basis',
			'flex-grow',
			'flex-shrink',
			'display',
			'flex-wrap',
			'flex-direction',
			'flex-order',
			'flex-pack',
			'flex-align',
			'align-items',
			'justify-content',
			'visibility',
			'float',
			'clear',
			'overflow',
			'overflow-x',
			'overflow-y',
			'overflow-scrolling',
			'clip',
			'zoom',
			'box-sizing',
			'width',
			'min-width',
			'max-width',
			'height',
			'min-height',
			'max-height',
			'margin',
			'margin-top',
			'margin-right',
			'margin-bottom',
			'margin-left',
			'padding',
			'padding-top',
			'padding-right',
			'padding-bottom',
			'padding-left',
			'table-layout',
			'empty-cells',
			'caption-side',
			'border-spacing',
			'border-collapse',
			'list-style',
			'list-style-position',
			'list-style-type',
			'list-style-image',
			'quotes',
			'counter-reset',
			'counter-increment',
			'font',
			'font-family',
			'font-size',
			'font-weight',
			'font-style',
			'font-variant',
			'font-size-adjust',
			'font-stretch',
			'font-effect',
			'font-emphasize',
			'font-emphasize-position',
			'font-emphasize-style',
			'font-smooth',
			'line-height',
			'text-align',
			'text-align-last',
			'vertical-align',
			'white-space',
			'text-decoration',
			'text-emphasis',
			'text-emphasis-color',
			'text-emphasis-style',
			'text-emphasis-position',
			'text-indent',
			'text-justify',
			'text-transform',
			'letter-spacing',
			'word-spacing',
			'writing-mode',
			'text-outline',
			'text-transform',
			'text-wrap',
			'text-overflow',
			'text-overflow-ellipsis',
			'text-overflow-mode',
			'word-wrap',
			'word-break',
			'tab-size',
			'hyphens',
			'resize',
			'cursor',
			'user-select',
			'nav-index',
			'nav-up',
			'nav-right',
			'nav-down',
			'nav-left',
			'transition',
			'transition-delay',
			'transition-timing-function',
			'transition-duration',
			'transition-property',
			'transform',
			'transform-origin',
			'animation',
			'animation-name',
			'animation-duration',
			'animation-play-state',
			'animation-timing-function',
			'animation-delay',
			'animation-iteration-count',
			'animation-iteration-count',
			'animation-direction',
			'pointer-events',
			'opacity',
			'interpolation-mode',
			'color',
			'border',
			'border-collapse',
			'border-width',
			'border-style',
			'border-color',
			'border-top',
			'border-top-width',
			'border-top-style',
			'border-top-color',
			'border-right',
			'border-right-width',
			'border-right-style',
			'border-right-color',
			'border-bottom',
			'border-bottom-width',
			'border-bottom-style',
			'border-bottom-color',
			'border-left',
			'border-left-width',
			'border-left-style',
			'border-left-color',
			'border-radius',
			'border-top-left-radius',
			'border-top-right-radius',
			'border-bottom-right-radius',
			'border-bottom-left-radius',
			'border-image',
			'border-image-source',
			'border-image-slice',
			'border-image-width',
			'border-image-outset',
			'border-image-repeat',
			'outline',
			'outline-width',
			'outline-style',
			'outline-color',
			'outline-offset',
			'background',
			'background-color',
			'background-image',
			'background-repeat',
			'background-attachment',
			'background-position',
			'background-position-x',
			'background-position-y',
			'background-clip',
			'background-origin',
			'background-size',
			'box-decoration-break',
			'box-shadow',
			'text-shadow',
		],
	},
};
